//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magicodes.IE.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Magicodes.IE.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An unknown error occurred in the template： 的本地化字符串。
        /// </summary>
        public static string AnUnknownErrorOccurredInTheTemplate {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurredInTheTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Append method must be called before the current method can be called! 的本地化字符串。
        /// </summary>
        public static string AppendMethodMustBeBeforeCurrentMethod {
            get {
                return ResourceManager.GetString("AppendMethodMustBeBeforeCurrentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A sheet with the name already exists 的本地化字符串。
        /// </summary>
        public static string ASheetWithTheNameAlreadyExists {
            get {
                return ResourceManager.GetString("ASheetWithTheNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column head repeat！ 的本地化字符串。
        /// </summary>
        public static string ColumnHeadRepeat {
            get {
                return ResourceManager.GetString("ColumnHeadRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data cannot be empty! 的本地化字符串。
        /// </summary>
        public static string DataCannotBeEmpty {
            get {
                return ResourceManager.GetString("DataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please define the header! 的本地化字符串。
        /// </summary>
        public static string DefineTheHeader {
            get {
                return ResourceManager.GetString("DefineTheHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not ignore all the header! 的本地化字符串。
        /// </summary>
        public static string DoNotIgnoreAllTheHeader {
            get {
                return ResourceManager.GetString("DoNotIgnoreAllTheHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error building expression: 的本地化字符串。
        /// </summary>
        public static string ErrorBuildingExpression {
            get {
                return ResourceManager.GetString("ErrorBuildingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Sheet attribute is not marked with the ExcelimporterAttribute attribute: 的本地化字符串。
        /// </summary>
        public static string ExcelimporterAttributeFeaturesIsNotAnnotated {
            get {
                return ResourceManager.GetString("ExcelimporterAttributeFeaturesIsNotAnnotated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data duplication exists, please check! Line： 的本地化字符串。
        /// </summary>
        public static string ExistDuplicateData {
            get {
                return ResourceManager.GetString("ExistDuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting &quot;.xlsx &quot;is only supported, that is, Excel97-2003 is not supported! 的本地化字符串。
        /// </summary>
        public static string ExportingIsOnlySupportedXLSX {
            get {
                return ResourceManager.GetString("ExportingIsOnlySupportedXLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Result 的本地化字符串。
        /// </summary>
        public static string ExportResult {
            get {
                return ResourceManager.GetString("ExportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name must be filled！ 的本地化字符串。
        /// </summary>
        public static string FileNameMustBeFilled {
            get {
                return ResourceManager.GetString("FileNameMustBeFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file name cannot be empty! 的本地化字符串。
        /// </summary>
        public static string FileNameShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("FileNameShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path cannot be empty! 的本地化字符串。
        /// </summary>
        public static string FilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("FilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 illegal！ 的本地化字符串。
        /// </summary>
        public static string Illegal {
            get {
                return ResourceManager.GetString("Illegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import data 的本地化字符串。
        /// </summary>
        public static string ImportData {
            get {
                return ResourceManager.GetString("ImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import file does not exist! 的本地化字符串。
        /// </summary>
        public static string ImportFileDoesNotExist {
            get {
                return ResourceManager.GetString("ImportFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This field is not found in the current import template! 的本地化字符串。
        /// </summary>
        public static string ImportTemplateNotFoundThisField {
            get {
                return ResourceManager.GetString("ImportTemplateNotFoundThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid data format！ 的本地化字符串。
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of allowed imports cannot be exceeded 的本地化字符串。
        /// </summary>
        public static string MaximumNumberImportsCannotExceeded {
            get {
                return ResourceManager.GetString("MaximumNumberImportsCannotExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 no 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only support exporting &quot;.csv &quot;! 的本地化字符串。
        /// </summary>
        public static string OnlySupportExportingCsv {
            get {
                return ResourceManager.GetString("OnlySupportExportingCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid, please fill in the correct date and time format! 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectDateAndTimeFormat {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectDateAndTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid, please fill in the correct decimal! 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectDecimal {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid, please fill in the correct GUID format! 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectGUIDFormat {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectGUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid, please fill in the correct integer value! 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectIntegerValue {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid, please fill in the correct timespan format! 的本地化字符串。
        /// </summary>
        public static string PleaseFillInTheCorrectTimeSpanFormat {
            get {
                return ResourceManager.GetString("PleaseFillInTheCorrectTimeSpanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template file path cannot be empty! 的本地化字符串。
        /// </summary>
        public static string TemplateFilePathCannotBeEmpty {
            get {
                return ResourceManager.GetString("TemplateFilePathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no template drop-down option! 的本地化字符串。
        /// </summary>
        public static string ThereAreNoTemplateDropDownOptions {
            get {
                return ResourceManager.GetString("ThereAreNoTemplateDropDownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong data 的本地化字符串。
        /// </summary>
        public static string WrongData {
            get {
                return ResourceManager.GetString("WrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
