using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Magicodes.IE.IO.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public sealed class XlsxRowGettersGenerator : IIncrementalGenerator
    {
        private sealed class TypeInfo
        {
            public TypeDeclarationSyntax? Syntax { get; set; }
            public INamedTypeSymbol? Symbol { get; set; }
        }

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: (node, _) => node is TypeDeclarationSyntax,
                transform: (ctx, _) =>
                {
                    if (ctx.Node is TypeDeclarationSyntax tds)
                    {
                        var sym = ctx.SemanticModel.GetDeclaredSymbol(tds);
                        if (sym is not null && HasAttr(sym) && sym is INamedTypeSymbol nts)
                            return new TypeInfo { Syntax = tds, Symbol = nts };
                    }
                    return null;
                })
                .Where(t => t is not null && t.Syntax is not null && t.Symbol is not null);

            var all = candidates.Collect();
            context.RegisterSourceOutput(all, (spc, items) => Emit(spc, items));
        }

        private static bool HasAttr(ISymbol sym)
        {
            const string expected = "global::Magicodes.IE.IO.XlsxExportableAttribute";
            foreach (var attr in sym.GetAttributes())
                if (attr.AttributeClass?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == expected)
                    return true;
            return false;
        }

        private static void Emit(SourceProductionContext spc, ImmutableArray<TypeInfo?> items)
        {
            if (items.IsDefaultOrEmpty) return;
            var seen = new HashSet<string>();

            foreach (var item in items)
            {
                if (item?.Symbol is null) continue;
                var named = item.Symbol;
                if (!seen.Add(named.ToDisplayString())) continue;

                try
                {
                    var source = Generate(named);
                    if (source is not null)
                        spc.AddSource($"XlsxGetters_{GetHintName(named)}.g.cs", SourceText.From(source, Encoding.UTF8));
                }
                catch (Exception ex)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "MIEIO001",
                            "XlsxRowGetters source generation failed",
                            "Source generation for type '{0}' failed: {1}",
                            "Magicodes.IE.IO.SourceGenerator",
                            DiagnosticSeverity.Warning,
                            isEnabledByDefault: true),
                        item.Syntax!.GetLocation(),
                        named.ToDisplayString(), ex.Message));
                }
            }
        }

        private static string? Generate(INamedTypeSymbol type)
        {
            if (type.IsGenericType || type.ContainingType is not null) return null;
            List<IPropertySymbol> props = new();
            foreach (var m in type.GetMembers())
            {
                if (m is IPropertySymbol p
                    && !p.IsStatic
                    && !p.IsIndexer
                    && p.GetMethod is not null
                    && p.GetMethod.DeclaredAccessibility == Accessibility.Public)
                    props.Add(p);
            }
            if (props.Count == 0) return null;

            var ns = GetNamespace(type);
            var name = type.Name;
            var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\r\n");
            sb.Append("#nullable enable\r\n");
            sb.Append("#pragma warning disable CS8600, CS8601, CS8603, CS8604, CS8619\r\n");
            sb.Append("\r\n");
            if (!string.IsNullOrEmpty(ns) && ns != "global")
            {
                sb.Append("namespace ").Append(ns).Append("\r\n{\r\n");
            }
            sb.Append("    internal static class ").Append(name).Append("_XlsxGetters\r\n");
            sb.Append("    {\r\n");

            foreach (var p in props)
            {
                sb.Append("        public static global::Magicodes.IE.IO.CellValue Get_").Append(p.Name)
                  .Append("(").Append(fullName).Append(" item) => ")
                  .Append(Expr(p, "item")).Append(";\r\n");
            }
            sb.Append("\r\n");

            sb.Append("        [System.Runtime.CompilerServices.ModuleInitializer]\r\n");
            sb.Append("        internal static void Register()\r\n");
            sb.Append("        {\r\n");
            sb.Append("            global::Magicodes.IE.IO.XlsxGeneratedGettersRegistry.Register<").Append(fullName).Append(">(() =>\r\n");
            sb.Append("            {\r\n");
            sb.Append("                var d = new System.Collections.Generic.Dictionary<string, System.Func<object?, global::Magicodes.IE.IO.CellValue>>(").Append(props.Count).Append(");\r\n");
            foreach (var p in props)
            {
                sb.Append("                d[\"").Append(p.Name).Append("\"] = obj =>\r\n");
                sb.Append("                {\r\n");
                sb.Append("                    var item = (").Append(fullName).Append(")obj!;\r\n");
                sb.Append("                    return ").Append(Expr(p, "item")).Append(";\r\n");
                sb.Append("                };\r\n");
            }
            sb.Append("                return d;\r\n");
            sb.Append("            });\r\n");
            sb.Append("            global::Magicodes.IE.IO.XlsxGeneratedTypedGettersRegistry.Register<").Append(fullName).Append(">(() =>\r\n");
            sb.Append("            {\r\n");
            sb.Append("                var td = new System.Collections.Generic.Dictionary<string, System.Func<").Append(fullName).Append(", global::Magicodes.IE.IO.CellValue>>(").Append(props.Count).Append(");\r\n");
            foreach (var p in props)
            {
                sb.Append("                td[\"").Append(p.Name).Append("\"] = Get_").Append(p.Name).Append(";\r\n");
            }
            sb.Append("                return td;\r\n");
            sb.Append("            });\r\n");
            EmitRowWriters(sb, props, fullName);
            EmitMetadata(sb, props, fullName);
            sb.Append("        }\r\n");
            sb.Append("    }\r\n");
            if (!string.IsNullOrEmpty(ns) && ns != "global") sb.Append("}\r\n");

            return sb.ToString();
        }

        private static void EmitRowWriters(StringBuilder sb, List<IPropertySymbol> props, string fullName)
        {
            sb.Append("            var __cw = new System.Collections.Generic.Dictionary<string, System.Action<global::Magicodes.IE.IO.XlsxWriter.XlsxRowWriter, ").Append(fullName).Append(", int>>(").Append(props.Count).Append(");\r\n");
            foreach (var p in props)
            {
                sb.Append("            __cw[\"").Append(p.Name).Append("\"] = (w, row, styleId) =>\r\n");
                sb.Append("            {\r\n");
                sb.Append("            ").Append(DirectWrite(p, "row." + EscapeIdentifier(p.Name), "styleId"));
                sb.Append("            };\r\n");
            }
            sb.Append("            global::Magicodes.IE.IO.XlsxGeneratedRowWritersRegistry.Register<").Append(fullName).Append(">(() => __cw);\r\n");
        }

        private static void EmitMetadata(StringBuilder sb, List<IPropertySymbol> props, string fullName)
        {
            sb.Append("            global::Magicodes.IE.IO.XlsxGeneratedTypeMetadataRegistry.Register<").Append(fullName).Append(">(() => new global::Magicodes.IE.IO.XlsxGeneratedPropertyMetadata<").Append(fullName).Append(">[]\r\n");
            sb.Append("            {\r\n");
            foreach (var p in props)
            {
                var exporter = GetAttribute(p, "ExporterHeaderAttribute");
                var importer = GetAttribute(p, "ImporterHeaderAttribute");
                var display = GetAttribute(p, "DisplayAttribute");
                var description = GetAttribute(p, "DescriptionAttribute");
                var displayFormat = GetAttribute(p, "DisplayFormatAttribute");
                var propertyType = GetParseType(p.Type);
                var setter = CanGenerateSetter(p)
                    ? "(item, cell, converters, date1904) =>\r\n                {\r\n"
                        + "                    if (!global::Magicodes.IE.IO.XlsxGeneratedReadHelper.TryParse<" + TypeName(propertyType) + ">(cell, out var value, converters, date1904)) return false;\r\n"
                        + "                    item." + EscapeIdentifier(p.Name) + " = value;\r\n"
                        + "                    return true;\r\n"
                        + "                }"
                    : "null";

                sb.Append("                new global::Magicodes.IE.IO.XlsxGeneratedPropertyMetadata<").Append(fullName).Append(">(\r\n");
                sb.Append("                    ").Append(Quote(p.Name)).Append(",\r\n");
                sb.Append("                    ").Append(Quote(GetNamedString(importer, "Name"))).Append(",\r\n");
                sb.Append("                    ").Append(Quote(GetNamedString(display, "Name"))).Append(",\r\n");
                sb.Append("                    ").Append(Quote(GetConstructorString(description))).Append(",\r\n");
                sb.Append("                    ").Append(Quote(GetNamedString(exporter, "Format") ?? GetNamedString(displayFormat, "DataFormatString"))).Append(",\r\n");
                sb.Append("                    ").Append(GetNamedDouble(exporter, "Width") is double width && width > 0 ? width.ToString(System.Globalization.CultureInfo.InvariantCulture) : "null").Append(",\r\n");
                sb.Append("                    ").Append(GetNamedInt(exporter, "Index")?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "-1").Append(",\r\n");
                sb.Append("                    ").Append(GetNamedBool(exporter, "IsIgnore") ? "true" : "false").Append(",\r\n");
                sb.Append("                    ").Append(Quote(propertyType.Name)).Append(",\r\n");
                sb.Append("                    Get_").Append(p.Name).Append(",\r\n");
                sb.Append("                    (w, row, styleId) =>\r\n");
                sb.Append("                    {\r\n");
                sb.Append(DirectWrite(p, "row." + EscapeIdentifier(p.Name), "styleId"));
                sb.Append("                    },\r\n");
                sb.Append("                    ").Append(setter).Append("),\r\n");
            }
            sb.Append("            });\r\n");
        }

        private static AttributeData? GetAttribute(IPropertySymbol property, string name)
        {
            foreach (var attribute in property.GetAttributes())
            {
                if (attribute.AttributeClass?.Name == name || attribute.AttributeClass?.Name == name.Replace("Attribute", string.Empty))
                    return attribute;
            }
            return null;
        }

        private static string? GetNamedString(AttributeData? attribute, string name)
        {
            if (attribute is null) return null;
            foreach (var argument in attribute.NamedArguments)
                if (argument.Key == name && argument.Value.Value is string value)
                    return value;
            return null;
        }

        private static bool GetNamedBool(AttributeData? attribute, string name)
        {
            if (attribute is null) return false;
            foreach (var argument in attribute.NamedArguments)
                if (argument.Key == name && argument.Value.Value is bool value)
                    return value;
            return false;
        }

        private static int? GetNamedInt(AttributeData? attribute, string name)
        {
            if (attribute is null) return null;
            foreach (var argument in attribute.NamedArguments)
                if (argument.Key == name && argument.Value.Value is int value)
                    return value;
            return null;
        }

        private static double? GetNamedDouble(AttributeData? attribute, string name)
        {
            if (attribute is null) return null;
            foreach (var argument in attribute.NamedArguments)
            {
                if (argument.Key == name && argument.Value.Value is double value)
                    return value;
            }
            return null;
        }

        private static string? GetConstructorString(AttributeData? attribute)
        {
            if (attribute is null || attribute.ConstructorArguments.Length == 0)
                return null;
            return attribute.ConstructorArguments[0].Value as string;
        }

        private static bool CanGenerateSetter(IPropertySymbol property)
        {
            return property.SetMethod is not null
                && property.SetMethod.DeclaredAccessibility == Accessibility.Public
                && !property.SetMethod.IsInitOnly;
        }

        private static ITypeSymbol GetParseType(ITypeSymbol type)
        {
            if (type is INamedTypeSymbol named
                && named.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
                return named.TypeArguments[0];
            return type;
        }

        private static string TypeName(ITypeSymbol type)
        {
            return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        private static string Quote(string? value)
        {
            if (value is null) return "null";
            var sb = new StringBuilder(value.Length + 2);
            sb.Append('"');
            foreach (var ch in value)
            {
                switch (ch)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\t': sb.Append("\\t"); break;
                    case '\0': sb.Append("\\0"); break;
                    default:
                        if (char.IsControl(ch))
                            sb.Append("\\u").Append(((int)ch).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                        else
                            sb.Append(ch);
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }

        private static string GetHintName(INamedTypeSymbol type)
        {
            var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var sb = new StringBuilder(full.Length);
            foreach (var ch in full)
                sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
            return sb.ToString();
        }

        private static string GetNamespace(INamedTypeSymbol type)
        {
            var ns = type.ContainingNamespace;
            if (ns is null || ns.IsGlobalNamespace) return string.Empty;
            var parts = new Stack<string>();
            while (ns is not null && !ns.IsGlobalNamespace)
            {
                parts.Push(ns.Name);
                ns = ns.ContainingNamespace;
            }
            return string.Join(".", parts);
        }

        private static string Expr(IPropertySymbol p, string v)
        {
            var u = Underlying(p.Type);
            var nullable = IsNullableValueType(p.Type);
            var access = $"{v}.{EscapeIdentifier(p.Name)}";
            if (nullable)
            {
                if (u.SpecialType == SpecialType.System_Int32) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromInteger({access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.SpecialType == SpecialType.System_Int64) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromInteger({access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.SpecialType == SpecialType.System_Double) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromNumber({access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.SpecialType == SpecialType.System_Single) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromNumber((double){access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.SpecialType == SpecialType.System_Decimal) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromNumber((double){access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.SpecialType == SpecialType.System_Boolean) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromBool({access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.SpecialType == SpecialType.System_DateTime) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromDateTime({access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (u.TypeKind == TypeKind.Enum)
                {
                    if (IsUlongEnum(u)) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromNumber((double)(ulong){access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                    return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromInteger((long){access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                }
                if (u.SpecialType == SpecialType.System_UInt64) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromNumber((double){access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                if (IsInt(u)) return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromInteger((long){access}.Value) : global::Magicodes.IE.IO.CellValue.Null";
                return $"{access}.HasValue ? global::Magicodes.IE.IO.CellValue.FromString({access}.Value.ToString()) : global::Magicodes.IE.IO.CellValue.Null";
            }
            if (u.SpecialType == SpecialType.System_String) return $"global::Magicodes.IE.IO.CellValue.FromString({access})";
            if (u.SpecialType == SpecialType.System_Int32) return $"global::Magicodes.IE.IO.CellValue.FromInteger({access})";
            if (u.SpecialType == SpecialType.System_Int64) return $"global::Magicodes.IE.IO.CellValue.FromInteger({access})";
            if (u.SpecialType == SpecialType.System_Double) return $"global::Magicodes.IE.IO.CellValue.FromNumber({access})";
            if (u.SpecialType == SpecialType.System_Decimal) return $"global::Magicodes.IE.IO.CellValue.FromNumber((double){access})";
            if (u.SpecialType == SpecialType.System_Boolean) return $"global::Magicodes.IE.IO.CellValue.FromBool({access})";
            if (u.TypeKind == TypeKind.Enum)
            {
                if (IsUlongEnum(u)) return $"global::Magicodes.IE.IO.CellValue.FromNumber((double)(ulong){access})";
                return $"global::Magicodes.IE.IO.CellValue.FromInteger((long){access})";
            }
            if (u.SpecialType == SpecialType.System_DateTime) return $"global::Magicodes.IE.IO.CellValue.FromDateTime({access})";
            if (u.SpecialType == SpecialType.System_Single) return $"global::Magicodes.IE.IO.CellValue.FromNumber((double){access})";
            if (u.SpecialType == SpecialType.System_UInt64) return $"global::Magicodes.IE.IO.CellValue.FromNumber((double){access})";
            if (IsInt(u)) return $"global::Magicodes.IE.IO.CellValue.FromInteger((long){access})";
            return $"global::Magicodes.IE.IO.CellValue.FromString({access}?.ToString())";
        }

        private static string DirectWrite(IPropertySymbol p, string access, string styleExpr)
        {
            var u = Underlying(p.Type);
            var nullable = IsNullableValueType(p.Type);
            var sb = new StringBuilder();

            if (nullable)
            {
                if (u.SpecialType == SpecialType.System_Int32 || u.SpecialType == SpecialType.System_Int64 || IsInt(u))
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteNumberCell(").Append(styleExpr).Append(", ").Append(access).Append(".Value); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (u.SpecialType == SpecialType.System_Double)
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteNumberCell(").Append(styleExpr).Append(", ").Append(access).Append(".Value); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (u.SpecialType == SpecialType.System_Single)
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteNumberCell(").Append(styleExpr).Append(", (double)").Append(access).Append(".Value); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (u.SpecialType == SpecialType.System_Decimal)
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteNumberCell(").Append(styleExpr).Append(", (double)").Append(access).Append(".Value); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (u.SpecialType == SpecialType.System_Boolean)
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteBoolCell(").Append(styleExpr).Append(", ").Append(access).Append(".Value); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (u.SpecialType == SpecialType.System_DateTime)
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteNumberCell(").Append(styleExpr).Append(", ").Append(access).Append(".Value.ToOADate()); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (IsDateTimeOffset(u))
                {
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteStringCell(").Append(styleExpr).Append(", ").Append(access).Append(".Value.ToString(\"O\", System.Globalization.CultureInfo.InvariantCulture)); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                if (u.TypeKind == TypeKind.Enum)
                {
                    var enumCast = IsUlongEnum(u) ? "(double)(ulong)" : "(long)";
                    sb.Append("            if (").Append(access).Append(".HasValue) w.WriteNumberCell(").Append(styleExpr).Append(", ").Append(enumCast).Append(access).Append(".Value); else w.WriteEmptyCell(").Append(styleExpr).Append(");\r\n");
                    return sb.ToString();
                }

                sb.Append("            if (").Append(access).Append(" is null) w.WriteEmptyCell(").Append(styleExpr).Append("); else w.WriteStringCell(").Append(styleExpr).Append(", ").Append(access).Append(".Value.ToString());\r\n");
                return sb.ToString();
            }

            if (u.SpecialType == SpecialType.System_String)
                return $"            w.WriteStringCell({styleExpr}, {access});\r\n";
            if (u.SpecialType == SpecialType.System_Int32 || u.SpecialType == SpecialType.System_Int64 || IsInt(u))
                return $"            w.WriteNumberCell({styleExpr}, {access});\r\n";
            if (u.SpecialType == SpecialType.System_Double)
                return $"            w.WriteNumberCell({styleExpr}, {access});\r\n";
            if (u.SpecialType == SpecialType.System_Single)
                return $"            w.WriteNumberCell({styleExpr}, (double){access});\r\n";
            if (u.SpecialType == SpecialType.System_Decimal)
                return $"            w.WriteNumberCell({styleExpr}, (double){access});\r\n";
            if (u.SpecialType == SpecialType.System_Boolean)
                return $"            w.WriteBoolCell({styleExpr}, {access});\r\n";
            if (u.SpecialType == SpecialType.System_DateTime)
                return $"            w.WriteNumberCell({styleExpr}, {access}.ToOADate());\r\n";
            if (IsDateTimeOffset(u))
                return $"            w.WriteStringCell({styleExpr}, {access}.ToString(\"O\", System.Globalization.CultureInfo.InvariantCulture));\r\n";
            if (u.TypeKind == TypeKind.Enum)
                return IsUlongEnum(u)
                    ? $"            w.WriteNumberCell({styleExpr}, (double)(ulong){access});\r\n"
                    : $"            w.WriteNumberCell({styleExpr}, (long){access});\r\n";
            return $"            w.WriteStringCell({styleExpr}, {access}?.ToString());\r\n";
        }

        private static ITypeSymbol Underlying(ITypeSymbol t)
        {
            if (t is INamedTypeSymbol n && n.ConstructedFrom?.ToString() == "System.Nullable<T>" && n.TypeArguments.Length == 1)
                return n.TypeArguments[0];
            return t;
        }

        private static bool IsNullableValueType(ITypeSymbol t) =>
            t is INamedTypeSymbol n
            && n.ConstructedFrom?.ToString() == "System.Nullable<T>"
            && n.TypeArguments.Length == 1;

        private static bool IsInt(ITypeSymbol t)
        {
            var s = t.SpecialType;
            return s == SpecialType.System_Int16 || s == SpecialType.System_Byte || s == SpecialType.System_SByte
                || s == SpecialType.System_UInt16 || s == SpecialType.System_UInt32 || s == SpecialType.System_UInt64;
        }

        private static bool IsUlongEnum(ITypeSymbol t)
        {
            return t.TypeKind == TypeKind.Enum
                && t is INamedTypeSymbol n
                && n.EnumUnderlyingType?.SpecialType == SpecialType.System_UInt64;
        }

        private static bool IsDateTimeOffset(ITypeSymbol t)
        {
            return t is INamedTypeSymbol n
                && n.SpecialType == SpecialType.None
                && n.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) == "global::System.DateTimeOffset";
        }

        private static string EscapeIdentifier(string name)
        {
            return Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
                || Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetContextualKeywordKind(name) != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
                ? "@" + name
                : name;
        }
    }
}
